stages:
  - test
  - build
  - deploy

# ... autres étapes du pipeline CI ...

# Étape pour le build et le push de l'image Docker
docker_build_and_push:
  stage: build
  script:
    - docker build -t nom-de-votre-image:tag .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  
    - docker push nom-de-votre-image:tag
  only:
    - feature/hajer/add-docker-buikd-push-step-to-ci
