name: Node.js CI
on:
  push:
     branches: 
          - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Change this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build and Push Docker Image
      run: docker build -t image .

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.Docker_sec }} -p ${{ secrets.DOCKER_pass }}
     
    - name: Tag Docker Image
      run: docker tag image ${{ secrets.Docker_sec }}/image:latest 
     
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.Docker_sec }}/image:latest

